# Generated by Django 5.2.8 on 2025-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cst_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cst_name', models.CharField(max_length=100)),
                ('Cst_contact', models.CharField(max_length=10)),
                ('Cst_gender', models.CharField(max_length=1)),
                ('Cst_dob', models.DateField()),
                ('Cst_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('Cst_address', models.TextField()),
                ('Cst_department', models.CharField(max_length=100)),
            ],
        ),
    ]
